from typing import Any

class Protocol:
    def __init__(self, app: Any) -> None: ...
    def connection_made(self, transport: Any) -> None: ...
    def data_received(self, data: bytes) -> None: ...
    def connection_lost(self, exc: Any) -> None: ...
